version: "3.9" # Or remove if desired
services:
  db:
    image: postgres:15-alpine
    container_name: taskq-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: taskq_user
      POSTGRES_PASSWORD: taskq_password
      POSTGRES_DB: taskq_db
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256 
    volumes:
      - taskq_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d/
  redis:
    image: redis:7-alpine
    container_name: taskq-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - taskq_redis_data:/data

volumes:
  taskq_data:
  taskq_redis_data: